services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: 'pR1zUYiQ'
      MYSQL_DATABASE: 'app-aiconversacional-itvs'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'w0OmG8IK'
    volumes:
      - 'db-volume:/var/lib/mysql'
    ports:
      - '9906:3306'
    restart: 'always'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
    build:
      context: '.'
      dockerfile: 'db/Dockerfile'
  web:
    depends_on:
      - 'db'
    ports:
      - '80:3000'   # Porta para o app web
      - '2222:22'   # Porta para o SSH (fora:container)
    restart: 'always'
    stdin_open: true
    tty: true
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/AzureAppService/web/Dockerfile'
volumes:
  db-volume: ~
