services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: 'Xx1lBsRy'
      MYSQL_DATABASE: 'app-aiconversacional-itvs'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'Z42JRs4z'
    volumes:
      - 'db-volume:/var/lib/mysql'
    ports:
      - '9906:3306'
    restart: 'always'
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
    build:
      context: '.'
      dockerfile: 'db/Dockerfile'
  web:
    depends_on:
      - 'db'
    ports:
      - '80:3000'
    restart: 'always'
    stdin_open: true
    tty: true
    logging:
      options:
        max-file: '5'
        max-size: '10m'
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/Hetzner Production/web/Dockerfile'
volumes:
  db-volume: ~
